version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.4.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: ember-cli
    versions:
    - 3.26.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: ember-template-lint
    versions:
    - 3.2.0
